version: "2.4"

services:
  sequencer:
    image: docker.io/geurto/generative-sequencer:sequencer-arm64
    privileged: true
    network_mode: host
    restart: always
    ipc: host
    pid: host
    command: ["/bin/bash", "-c", "/home/sequencer/init.sh"]