version: "2.4"

services:
  sequencer:
    image: docker.io/geurto/generative-sequencer:sequencer-amd64
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - "DISPLAY=$DISPLAY"
    ipc: host
    pid: host
    command: ["sleep", "infinity"]